<a href="https://colab.research.google.com/github/Moximixi/Emotional-analysis-of-curriculum-review/blob/main/LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!wget https://raw.githubusercontent.com/Moximixi/Emotional-analysis-of-curriculum-review/main/%E9%BB%84%E5%BF%A0%E8%B4%A2/newtest.csv

--2021-04-18 10:48:30--  https://raw.githubusercontent.com/Moximixi/Emotional-analysis-of-curriculum-review/main/%E9%BB%84%E5%BF%A0%E8%B4%A2/newtest.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 843462 (824K) [text/plain]
Saving to: ‘newtest.csv’

newtest.csv         100%[===================>] 823.69K  --.-KB/s    in 0.05s   

2021-04-18 10:48:30 (15.1 MB/s) - ‘newtest.csv’ saved [843462/843462]



数据文件导入，分开导入评论语句和情感标签

In [4]:
import pandas as pd
import numpy as np
comment = pd.read_csv("newtest.csv",usecols=['comment'])
sentiment = pd.read_csv("newtest.csv",usecols=['sentiment'])

In [5]:
!pip install compiler.ast


ERROR: Could not find a version that satisfies the requirement compiler.ast (from versions: none)
ERROR: No matching distribution found for compiler.ast


将评论语句转为list类型

In [6]:
comment_array = np.array(comment)
comment_lst = comment_array.tolist()
print(comment_lst)
from itertools import chain
comment_list = list(chain.from_iterable(comment_lst))
# comment_list

[['讲的能不能详细一点，一个视频六分钟？六分钟我就学会了？'], ['讲题的时候能不能把电路图在解析的那一页加上，要不然还要画下来或者翻来覆去的看'], ['垃圾，垃圾，垃圾'], ['希望演示时镜头可以不一直移动，对于这种课程来说，镜头一直移动导致看不清动作变换，根本没法学习，这真的令人非常的失望。'], ['貌似有点慢\n'], ['听不懂啊啊啊啊'], ['理解理解理解.'], ['觉得mooc算平时成绩真的不合理，有些人。。。老实人吃亏\n'], ['无聊，没意义'], ['证书太便宜了'], ['很多时候我无法完全记忆什么时候有作业，这使得我错过了很多次作业，可以加个提醒机制吗'], ['mooc做的真的差劲\n'], ['难以理解，不够生动形象'], ['为什么找不到后面三节的'], ['课后习题很多都是课程里面没有讲到的，有点超纲了'], ['很好，课程知识点基本完整，但是少了一些基本操作的算法和程序讲解，另外，可以加上一些经典案例的讲解'], ['按时听课完成作业结果没有证书，真是让人头大'], ['课程讲解过于死板，不能调动学生的兴趣'], ['一个学期都没消息，以为没人管理了，结果这个分数是怎么算的呢'], ['不好！！！！'], ['看完之后更新好慢，而且换电脑了，更新又不知道，'], ['评分机制不清晰，不能直观体现，上完的单元课没有标记，移动端没有移植电脑端的所有功能，对iPad的优化太差'], ['有些听了几遍还是不明白，我太蠢了'], ['学习进度条不够明确，没有明确显示未学习内容'], ['内容挺丰富的，但是老师的用词太过于简单如“very very”不能生动地体现所表达的意境，讲解时用的句式略带有中式思维，如“the number 3 point”，课程讲解应该避免过多的“how to say”这种插入语。老师的发音偏美式。对于高水平英语学习者的话，不太建议听。老师的经验是很丰富的，举得例子也很助于理解，但我个人只从语言方面来评价，仅供参考'], ['文档 一直打不开，手机电脑不同步，系统有待提升。'], ['作业题干设定不明确，容易产生歧义\n课程讲述不详细，学习时大部分时间依赖网络其他资源'], ['课程繁琐 任务太杂\n\n'], ['没必要做这个课程，全部在照书念'], ['经常做了却显示未完成'], ['平台上需完成的作

进行分词，然后生成vocb词典

In [7]:
import jieba
words_list = []
for sentence in comment_list:
  words_list.append([jieba.cut(sentence)])


# words_list = [jieba.cut(com) for com in comment_list]
print(words_list)

# print(" ".join(words_list[1]))
v = []
for words in words_list:
  for word in words:
    v.append([w for w in word])
print(v)
#情感句子分词后的二维list

words_list1 = [list(jieba.cut(comment)) for comment in comment_list]
vocb = set([word for words in words_list1 for word in words])
print(vocb)


Building prefix dict from the default dictionary ...


[[<generator object Tokenizer.cut at 0x7f91760b33d0>], [<generator object Tokenizer.cut at 0x7f91760b3450>], [<generator object Tokenizer.cut at 0x7f91760b34d0>], [<generator object Tokenizer.cut at 0x7f91760b3550>], [<generator object Tokenizer.cut at 0x7f91760b35d0>], [<generator object Tokenizer.cut at 0x7f91760b3650>], [<generator object Tokenizer.cut at 0x7f91760b36d0>], [<generator object Tokenizer.cut at 0x7f91760b3750>], [<generator object Tokenizer.cut at 0x7f91760b37d0>], [<generator object Tokenizer.cut at 0x7f91760b38d0>], [<generator object Tokenizer.cut at 0x7f91760b3950>], [<generator object Tokenizer.cut at 0x7f91760b39d0>], [<generator object Tokenizer.cut at 0x7f91760b3a50>], [<generator object Tokenizer.cut at 0x7f91760b3ad0>], [<generator object Tokenizer.cut at 0x7f91760b3b50>], [<generator object Tokenizer.cut at 0x7f91760b3bd0>], [<generator object Tokenizer.cut at 0x7f91760b3c50>], [<generator object Tokenizer.cut at 0x7f91760b3850>], [<generator object Tokenize

Dumping model to file cache /tmp/jieba.cache
Loading model cost 1.120 seconds.
Prefix dict has been built successfully.


[['讲', '的', '能', '不能', '详细', '一点', '，', '一个', '视频', '六分钟', '？', '六分钟', '我', '就', '学会', '了', '？'], ['讲题', '的', '时候', '能', '不能', '把', '电路图', '在', '解析', '的', '那', '一页', '加上', '，', '要不然', '还要', '画', '下来', '或者', '翻来覆去', '的', '看'], ['垃圾', '，', '垃圾', '，', '垃圾'], ['希望', '演示', '时', '镜头', '可以', '不', '一直', '移动', '，', '对于', '这种', '课程', '来说', '，', '镜头', '一直', '移动', '导致', '看不清', '动作', '变换', '，', '根本', '没法', '学习', '，', '这', '真的', '令人', '非常', '的', '失望', '。'], ['貌似', '有点', '慢', '\n'], ['听不懂', '啊啊啊', '啊'], ['理解', '理解', '理解', '.'], ['觉得', 'mooc', '算', '平时成绩', '真的', '不合理', '，', '有些', '人', '。', '。', '。', '老实人', '吃亏', '\n'], ['无聊', '，', '没', '意义'], ['证书', '太', '便宜', '了'], ['很多', '时候', '我', '无法', '完全', '记忆', '什么', '时候', '有', '作业', '，', '这', '使得', '我', '错过', '了', '很', '多次', '作业', '，', '可以', '加个', '提醒', '机制', '吗'], ['mooc', '做', '的', '真的', '差劲', '\n'], ['难以', '理解', '，', '不够', '生动', '形象'], ['为什么', '找', '不到', '后面', '三节', '的'], ['课后', '习题', '很多', '都', '是', '课程', '里面', '没有', '讲到', '的', '，', '有点', '超纲', '了'], ['很',

word_to_idx：{'单词':序号,...}
idx_to_word：{序号:'单词',...}

In [8]:

word_to_idx = {word: i for i, word in enumerate(vocb,1)}
idx_to_word = {word_to_idx[word]: word for word in word_to_idx}



In [9]:
print(word_to_idx)
print(idx_to_word)

{'总打': 1, '任课老师': 2, '必胜信念': 3, '侧验': 4, '鸡丝': 5, '我怕': 6, '24': 7, '重来': 8, '长处': 9, '会议': 10, '而是': 11, '一新': 12, '马克思': 13, '爷': 14, '补': 15, '新民主主义': 16, '稍微': 17, '讲得': 18, '早早': 19, '及时性': 20, '无意间': 21, '忽大忽小': 22, '教案': 23, '智慧': 24, '语言': 25, '人民战争': 26, '饮食': 27, '干活': 28, '那不考': 29, '能否': 30, '托': 31, '跟得上': 32, '尤': 33, '检测': 34, '常态': 35, '浅浅': 36, '反应': 37, '没点': 38, '最后': 39, '不好玩': 40, '鼓励': 41, '去掉': 42, '南理工': 43, '做人': 44, '几节课': 45, '有助于': 46, '亲身经历': 47, '多媒体': 48, '趋势': 49, '限度': 50, '提高效率': 51, '误区': 52, '追剧': 53, '注重': 54, '想学点': 55, '11111': 56, '地去': 57, '举得': 58, '提纲': 59, '营业': 60, '亲耳': 61, '不放': 62, '东一句西': 63, '相比之下': 64, '吾': 65, '识字': 66, '通顺': 67, '漂亮': 68, '三个': 69, '难度': 70, '将近': 71, '认真完成': 72, '不屑': 73, '人性化': 74, '自然科学': 75, '学系': 76, '流利': 77, '超时': 78, '帐号': 79, '1.19': 80, '打好': 81, '╥': 82, '困': 83, '生儿育女': 84, '题太多': 85, '分割线': 86, '偏颇': 87, '遭遇': 88, 'Bug': 89, '自信': 90, '吸引': 91, 'xian': 92, '在线视频': 93, '半圆': 94, '小学': 95, '美好': 96, '公众': 

label标签

In [10]:
labels = np.array(sentiment)
labels = labels.flatten()
print(labels)

[0 0 0 ... 1 1 1]


将评论分词后的词语一一转化为整数

In [11]:

vocb_ints = []
for vocb in v:
    vocb_ints.append([word_to_idx[word] for word in vocb])

In [12]:
print(vocb_ints[:1])

[[2060, 9820, 8447, 4581, 5361, 4077, 2369, 2340, 10280, 2722, 1446, 2722, 1240, 4105, 3089, 8566, 1446]]


In [13]:
for i in vocb_ints[0]:
  print(idx_to_word[i],end='')


讲的能不能详细一点，一个视频六分钟？六分钟我就学会了？

In [14]:
length_v = []
for i in vocb_ints:
  length_v.append(len(i))
average_len = sum(length_v)/len(length_v)
print(average_len)
print(max(length_v))

14.93557224922669
494


## Padding sequences
将所有句子统一长度为50个单词：
1、评论长度小于50的，我们对其左边填充0
2、对于大于50的，我们只截取其前50个单词

In [15]:
def pad_features(vocb_ints, seq_length):
    ''' Return features of review_ints, where each review is padded with 0's 
        or truncated to the input seq_length.
    '''
    
    # getting the correct rows x cols shape
    features = np.zeros((len(vocb_ints), seq_length), dtype=int)
    print(features.shape)
    # for each review, I grab that review and 
    for i, row in enumerate(vocb_ints):
        features[i, -len(row):] = np.array(row)[:seq_length]
    
    return features
 
 
 
# Test your implementation!
 
#选择每个句子长为50

seq_length = 50
 
features = pad_features(vocb_ints, seq_length=seq_length)
 
## test statements - do not change - ##
assert len(features)==len(vocb_ints), "Your features should have as many rows as reviews."
assert len(features[0])==seq_length, "Each feature row should contain seq_length values."
 
# print first 10 values of the first 30 batches 
print(features[:30,:10])

(11315, 50)
[[    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0

### Training, Test划分

In [16]:
split_frac = 0.8
 
## split data into training, validation, and test data (features and labels, x and y)
 
split_idx = int(len(features)*split_frac)
train_x, remaining_x = features[:split_idx], features[split_idx:]
train_y, remaining_y = labels[:split_idx], labels[split_idx:]
 
test_idx = int(len(remaining_x)*0.5)
val_x, test_x = remaining_x[:test_idx], remaining_x[test_idx:]
val_y, test_y = remaining_y[:test_idx], remaining_y[test_idx:]
 
## print out the shapes of your resultant feature data
print("\t\t\tFeature Shapes:")
print("Train set: \t\t{}".format(train_x.shape), 
      "\nValidation set: \t{}".format(val_x.shape),
      "\nTest set: \t\t{}".format(test_x.shape))

			Feature Shapes:
Train set: 		(9052, 50) 
Validation set: 	(1131, 50) 
Test set: 		(1132, 50)


或者

In [ ]:
# 无运行，但他可以随机化
from sklearn.model_selection import ShuffleSplit
ss = ShuffleSplit(n_splits=1,test_size=0.2,random_state=0)
for train_index,test_index in ss.split(np.array(reviews_ints)):
    train_x = features[train_index]
    train_y = labels[train_index]
    test_x = features[test_index]
    test_y = labels[test_index]
 
print("\t\t\tFeature Shapes:")
print("Train set: \t\t{}".format(train_x.shape), 
      "\nTrain_Y set: \t{}".format(train_y.shape),
      "\nTest set: \t\t{}".format(test_x.shape))

DataLoaders and Batching

In [35]:
import torch
from torch.utils.data import TensorDataset, DataLoader
 
# create Tensor datasets
train_data = TensorDataset(torch.from_numpy(train_x), torch.from_numpy(train_y))
valid_data = TensorDataset(torch.from_numpy(val_x), torch.from_numpy(val_y))
test_data = TensorDataset(torch.from_numpy(test_x), torch.from_numpy(test_y))
 
# dataloaders
batch_size = 50

# make sure the SHUFFLE your training data
train_loader = DataLoader(train_data, shuffle=True, batch_size=batch_size,drop_last=True)
valid_loader = DataLoader(valid_data, shuffle=True, batch_size=batch_size,drop_last=True)
test_loader = DataLoader(test_data, shuffle=True, batch_size=batch_size,drop_last=True)

In [37]:

# obtain one batch of training data
dataiter = iter(train_loader)
sample_x, sample_y = dataiter.next()
 
print('Sample input size: ', sample_x.size()) # batch_size, seq_length
print('Sample input: \n', sample_x)
print()
print('Sample label size: ', sample_y.size()) # batch_size
print('Sample label: \n', sample_y)


Sample input size:  torch.Size([50, 50])
Sample input: 
 tensor([[    0,     0,     0,  ...,  5135,  1621,  1661],
        [    0,     0,     0,  ..., 10339,   175,  1661],
        [ 9289, 10608,  2369,  ...,  1240,  3636,  8566],
        ...,
        [    0,     0,     0,  ...,  2476,  2369,  6466],
        [    0,     0,     0,  ...,  2326,   575,  2573],
        [    0,     0,     0,  ...,  3991,  8566,   810]])

Sample label size:  torch.Size([50])
Sample label: 
 tensor([0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
        0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
        0, 0])


双向LSTM模型
1. 判断是否有GPU

In [38]:
# First checking if GPU is available
train_on_gpu=torch.cuda.is_available()
 
if(train_on_gpu):
    print('Training on GPU.')
else:
    print('No GPU available, training on CPU.')

Training on GPU.


In [39]:
import torch.nn as nn
 
class SentimentRNN(nn.Module):
    """
    The RNN model that will be used to perform Sentiment analysis.
    """
 
    def __init__(self, vocab_size, output_size, embedding_dim, hidden_dim, n_layers, bidirectional=True, drop_prob=0.5):
        """
        Initialize the model by setting up the layers.
        """
        super(SentimentRNN, self).__init__()
 
        self.output_size = output_size
        self.n_layers = n_layers
        self.hidden_dim = hidden_dim
        self.bidirectional = bidirectional
        
        # embedding and LSTM layers
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, n_layers, 
                            dropout=drop_prob, batch_first=True,
                            bidirectional=bidirectional)
        
        # dropout layer
        self.dropout = nn.Dropout(0.3)
        
        # linear and sigmoid layers
        if bidirectional:
          self.fc = nn.Linear(hidden_dim*2, output_size)
        else:
          self.fc = nn.Linear(hidden_dim, output_size)
          
        self.sig = nn.Sigmoid()
        
 
    def forward(self, x, hidden):
        """
        Perform a forward pass of our model on some input and hidden state.
        """
        batch_size = x.size(0)
 
        # embeddings and lstm_out
        x = x.long()
        embeds = self.embedding(x)
        lstm_out, hidden = self.lstm(embeds, hidden)
        
#         if bidirectional:
#           lstm_out = lstm_out.contiguous().view(-1, self.hidden_dim*2)
#         else:
#           lstm_out = lstm_out.contiguous().view(-1, self.hidden_dim)
       
        # dropout and fully-connected layer
        out = self.dropout(lstm_out)
        out = self.fc(out)
        # sigmoid function
        sig_out = self.sig(out)
        
        # reshape to be batch_size first
        sig_out = sig_out.view(batch_size, -1)
        sig_out = sig_out[:, -1] # get last batch of labels
        
        # return last sigmoid output and hidden state
        return sig_out, hidden
    
    
    def init_hidden(self, batch_size):
        ''' Initializes hidden state '''
        # Create two new tensors with sizes n_layers x batch_size x hidden_dim,
        # initialized to zero, for hidden state and cell state of LSTM
        weight = next(self.parameters()).data
        
        number = 1
        if self.bidirectional:
           number = 2
        
        if (train_on_gpu):
            hidden = (weight.new(self.n_layers*number, batch_size, self.hidden_dim).zero_().cuda(),
                      weight.new(self.n_layers*number, batch_size, self.hidden_dim).zero_().cuda()
                     )
        else:
            hidden = (weight.new(self.n_layers*number, batch_size, self.hidden_dim).zero_(),
                      weight.new(self.n_layers*number, batch_size, self.hidden_dim).zero_()
                     )
        
        return hidden

是否使用双向LSTM（在测试集上效果更好一些）





In [40]:
# Instantiate the model w/ hyperparams
vocab_size = len(word_to_idx)+1  # +1 for the 0 padding + our word tokens
output_size = 1
embedding_dim = 400
hidden_dim = 256
n_layers = 2
bidirectional = False  #这里为True，为双向LSTM
 
net = SentimentRNN(vocab_size, output_size, embedding_dim, hidden_dim, n_layers, bidirectional)
 
print(net)

SentimentRNN(
  (embedding): Embedding(11043, 400)
  (lstm): LSTM(400, 256, num_layers=2, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.3, inplace=False)
  (fc): Linear(in_features=256, out_features=1, bias=True)
  (sig): Sigmoid()
)


### train



In [41]:
# loss and optimization functions
lr=0.001
 
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(net.parameters(), lr=lr)
 
 
# training params
 
epochs = 4 # 3-4 is approx where I noticed the validation loss stop decreasing
 
print_every = 100
clip=5 # gradient clipping
 
# move model to GPU, if available
if(train_on_gpu):
    net.cuda()
 
net.train()
# train for some number of epochs
for e in range(epochs):
    # initialize hidden state
    h = net.init_hidden(batch_size)
    counter = 0
 
    # batch loop
    for inputs, labels in train_loader:
        counter += 1
 
        if(train_on_gpu):
            inputs, labels = inputs.cuda(), labels.cuda()
 
        # Creating new variables for the hidden state, otherwise
        # we'd backprop through the entire training history
        h = tuple([each.data for each in h])
        # zero accumulated gradients
        net.zero_grad()
 
        # get the output from the model
        output, h = net(inputs, h)
 
        # calculate the loss and perform backprop
        loss = criterion(output.squeeze(), labels.float())
        loss.backward()
        # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
        nn.utils.clip_grad_norm_(net.parameters(), clip)
        optimizer.step()
 
        # loss stats
        if counter % print_every == 0:
            # Get validation loss
            val_h = net.init_hidden(batch_size)
            val_losses = []
            net.eval()
            for inputs, labels in valid_loader:
 
                # Creating new variables for the hidden state, otherwise
                # we'd backprop through the entire training history
                val_h = tuple([each.data for each in val_h])
 
                if(train_on_gpu):
                    inputs, labels = inputs.cuda(), labels.cuda()
 
                output, val_h = net(inputs, val_h)
                val_loss = criterion(output.squeeze(), labels.float())
 
                val_losses.append(val_loss.item())
 
            net.train()
            print("Epoch: {}/{}...".format(e+1, epochs),
                  "Step: {}...".format(counter),
                  "Loss: {:.6f}...".format(loss.item()),
                  "Val Loss: {:.6f}".format(np.mean(val_losses)))

Epoch: 1/4... Step: 100... Loss: 0.306278... Val Loss: 0.243635
Epoch: 2/4... Step: 100... Loss: 0.090837... Val Loss: 0.251084
Epoch: 3/4... Step: 100... Loss: 0.136640... Val Loss: 0.304758
Epoch: 4/4... Step: 100... Loss: 0.400385... Val Loss: 0.251925


### Test

In [42]:
# Get test data loss and accuracy
 
test_losses = [] # track loss
num_correct = 0
 
# init hidden state
h = net.init_hidden(batch_size)
 
net.eval()
# iterate over test data
for inputs, labels in test_loader:
 
    # Creating new variables for the hidden state, otherwise
    # we'd backprop through the entire training history
    h = tuple([each.data for each in h])
 
    if(train_on_gpu):
        inputs, labels = inputs.cuda(), labels.cuda()
    
    # get predicted outputs
    output, h = net(inputs, h)
    
    # calculate loss
    test_loss = criterion(output.squeeze(), labels.float())
    test_losses.append(test_loss.item())
    
    # convert output probabilities to predicted class (0 or 1)
    pred = torch.round(output.squeeze())  # rounds to the nearest integer
    
    # compare predictions to true label
    correct_tensor = pred.eq(labels.float().view_as(pred))
    correct = np.squeeze(correct_tensor.numpy()) if not train_on_gpu else np.squeeze(correct_tensor.cpu().numpy())
    num_correct += np.sum(correct)
 
 
# -- stats! -- ##
# avg test loss
print("Test loss: {:.3f}".format(np.mean(test_losses)))
 
# accuracy over all test data
test_acc = num_correct/len(test_loader.dataset)
print("Test accuracy: {:.3f}".format(test_acc))

Test loss: 0.331
Test accuracy: 0.883


### 模型Inference

In [54]:
# negative test review
test_review_neg = '这老师只念PPT也太敷衍了吧'


In [55]:

 
def tokenize_review(test_review):
    test_cut = jieba.cut(test_review) #分词
    test_words = [word for word in test_cut]  #输出jieba迭代器
    # get rid of punctuation

    # tokens
    test_ints = []
    test_ints.append([word_to_idx[word] for word in test_words])
 
    return test_ints
 
# test code and generate tokenized review
test_ints = tokenize_review(test_review_neg)
print(test_ints)
 
 
# test sequence padding
seq_length=200
features = pad_features(test_ints, seq_length)
print(features)
 
# test conversion to tensor and pass into your model
feature_tensor = torch.from_numpy(features)
print(feature_tensor.size())

[[6795, 8542, 4872, 877, 2326, 10376, 10090, 8566, 2395]]
(1, 200)
[[    0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0  

In [56]:
def predict(net, test_review, sequence_length=50):
    
    net.eval()
    
    # tokenize review
    test_ints = tokenize_review(test_review)
    
    # pad tokenized sequence
    seq_length=sequence_length
    features = pad_features(test_ints, seq_length)
    
    # convert to tensor to pass into your model
    feature_tensor = torch.from_numpy(features)
    
    batch_size = feature_tensor.size(0)
    
    # initialize hidden state
    h = net.init_hidden(batch_size)
    
    if(train_on_gpu):
        feature_tensor = feature_tensor.cuda()
    
    # get the output from the model
    output, h = net(feature_tensor, h)
    
    # convert output probabilities to predicted class (0 or 1)
    pred = torch.round(output.squeeze()) 
    # printing output value, before rounding
    print('Prediction value, pre-rounding: {:.6f}'.format(output.item()))
    
    # print custom response
    if(pred.item()==1):
        print("Positive review detected!")
    else:
        print("Negative review detected.")

In [60]:

 
# call function
seq_length=50 # good to use the length that was trained on
 
predict(net, test_review_neg, seq_length)

(1, 50)
Prediction value, pre-rounding: 0.000507
Negative review detected.


In [61]:
# positive test review
test_review_pos = '这个课的老师讲的真不错'
predict(net, test_review_pos, seq_length)

(1, 50)
Prediction value, pre-rounding: 0.930878
Positive review detected!
