In [ ]:
!wget https://raw.githubusercontent.com/Moximixi/Emotional-analysis-of-curriculum-review/main/%E9%BB%84%E5%BF%A0%E8%B4%A2/newtest.csv

--2021-04-25 17:25:34--  https://raw.githubusercontent.com/Moximixi/Emotional-analysis-of-curriculum-review/main/%E9%BB%84%E5%BF%A0%E8%B4%A2/newtest.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 843462 (824K) [text/plain]
Saving to: ‘newtest.csv.12’

newtest.csv.12      100%[===================>] 823.69K  --.-KB/s    in 0.02s   

2021-04-25 17:25:34 (46.2 MB/s) - ‘newtest.csv.12’ saved [843462/843462]



数据文件导入，分开导入评论语句和情感标签

In [ ]:
import pandas as pd
import numpy as np
comment = pd.read_csv("newtest.csv",usecols=['comment'])
sentiment = pd.read_csv("newtest.csv",usecols=['sentiment'])

将评论语句转为list类型

In [ ]:
comment_array = np.array(comment)
comment_lst = comment_array.tolist()
print(comment_lst)
from itertools import chain
comment_list_p = list(chain.from_iterable(comment_lst))
# comment_list

[['讲的能不能详细一点，一个视频六分钟？六分钟我就学会了？'], ['讲题的时候能不能把电路图在解析的那一页加上，要不然还要画下来或者翻来覆去的看'], ['垃圾，垃圾，垃圾'], ['希望演示时镜头可以不一直移动，对于这种课程来说，镜头一直移动导致看不清动作变换，根本没法学习，这真的令人非常的失望。'], ['貌似有点慢\n'], ['听不懂啊啊啊啊'], ['理解理解理解.'], ['觉得mooc算平时成绩真的不合理，有些人。。。老实人吃亏\n'], ['无聊，没意义'], ['证书太便宜了'], ['很多时候我无法完全记忆什么时候有作业，这使得我错过了很多次作业，可以加个提醒机制吗'], ['mooc做的真的差劲\n'], ['难以理解，不够生动形象'], ['为什么找不到后面三节的'], ['课后习题很多都是课程里面没有讲到的，有点超纲了'], ['很好，课程知识点基本完整，但是少了一些基本操作的算法和程序讲解，另外，可以加上一些经典案例的讲解'], ['按时听课完成作业结果没有证书，真是让人头大'], ['课程讲解过于死板，不能调动学生的兴趣'], ['一个学期都没消息，以为没人管理了，结果这个分数是怎么算的呢'], ['不好！！！！'], ['看完之后更新好慢，而且换电脑了，更新又不知道，'], ['评分机制不清晰，不能直观体现，上完的单元课没有标记，移动端没有移植电脑端的所有功能，对iPad的优化太差'], ['有些听了几遍还是不明白，我太蠢了'], ['学习进度条不够明确，没有明确显示未学习内容'], ['内容挺丰富的，但是老师的用词太过于简单如“very very”不能生动地体现所表达的意境，讲解时用的句式略带有中式思维，如“the number 3 point”，课程讲解应该避免过多的“how to say”这种插入语。老师的发音偏美式。对于高水平英语学习者的话，不太建议听。老师的经验是很丰富的，举得例子也很助于理解，但我个人只从语言方面来评价，仅供参考'], ['文档 一直打不开，手机电脑不同步，系统有待提升。'], ['作业题干设定不明确，容易产生歧义\n课程讲述不详细，学习时大部分时间依赖网络其他资源'], ['课程繁琐 任务太杂\n\n'], ['没必要做这个课程，全部在照书念'], ['经常做了却显示未完成'], ['平台上需完成的作

去掉符号

In [ ]:
import re
def removePunctuation(content):
        """
        文本去标点
        """
        punctuation = r"~!@#$%^&*()_+`{}|\[\]\:\";\-\\\='<>?,./，。、《》？；：‘“{【】}|、！@#￥%……&*（）——+=-"
        content = re.sub(r'[{}]+'.format(punctuation), '', content)
        return content.strip().lower()
comment_list=[]
for index in range(len(comment_list_p)):
  comment_list.append([removePunctuation(str(comment_list_p[index]))])
print(comment_list)
print(type(comment_list[0]))

[['讲的能不能详细一点一个视频六分钟六分钟我就学会了'], ['讲题的时候能不能把电路图在解析的那一页加上要不然还要画下来或者翻来覆去的看'], ['垃圾垃圾垃圾'], ['希望演示时镜头可以不一直移动对于这种课程来说镜头一直移动导致看不清动作变换根本没法学习这真的令人非常的失望'], ['貌似有点慢'], ['听不懂啊啊啊啊'], ['理解理解理解'], ['觉得mooc算平时成绩真的不合理有些人老实人吃亏'], ['无聊没意义'], ['证书太便宜了'], ['很多时候我无法完全记忆什么时候有作业这使得我错过了很多次作业可以加个提醒机制吗'], ['mooc做的真的差劲'], ['难以理解不够生动形象'], ['为什么找不到后面三节的'], ['课后习题很多都是课程里面没有讲到的有点超纲了'], ['很好课程知识点基本完整但是少了一些基本操作的算法和程序讲解另外可以加上一些经典案例的讲解'], ['按时听课完成作业结果没有证书真是让人头大'], ['课程讲解过于死板不能调动学生的兴趣'], ['一个学期都没消息以为没人管理了结果这个分数是怎么算的呢'], ['不好'], ['看完之后更新好慢而且换电脑了更新又不知道'], ['评分机制不清晰不能直观体现上完的单元课没有标记移动端没有移植电脑端的所有功能对ipad的优化太差'], ['有些听了几遍还是不明白我太蠢了'], ['学习进度条不够明确没有明确显示未学习内容'], ['内容挺丰富的但是老师的用词太过于简单如very very”不能生动地体现所表达的意境讲解时用的句式略带有中式思维如the number 3 point”课程讲解应该避免过多的how to say”这种插入语老师的发音偏美式对于高水平英语学习者的话不太建议听老师的经验是很丰富的举得例子也很助于理解但我个人只从语言方面来评价仅供参考'], ['文档 一直打不开手机电脑不同步系统有待提升'], ['作业题干设定不明确容易产生歧义\n课程讲述不详细学习时大部分时间依赖网络其他资源'], ['课程繁琐 任务太杂'], ['没必要做这个课程全部在照书念'], ['经常做了却显示未完成'], ['平台上需完成的作业内容太多了评论区大量的内容并不能使师生良好交流极大加重了学习压力'], ['网课难道就是把ppt念一遍吗'], ['本来对这课满怀期待两个月前

进行分词，然后生成vocb词典

In [ ]:
import jieba
words_list = []
for comment in comment_list:
  for sentence in comment:
    words_list.append([jieba.cut(sentence)])


# words_list = [jieba.cut(com) for com in comment_list]
print(words_list)

# print(" ".join(words_list[1]))
v = []
for words in words_list:
  for word in words:
    v.append([w for w in word])
print(v)
#情感句子分词后的二维list

vocb = set([word for words in v for word in words])
print(vocb)


[[<generator object Tokenizer.cut at 0x7f90a8466550>], [<generator object Tokenizer.cut at 0x7f90a84665d0>], [<generator object Tokenizer.cut at 0x7f90a8466650>], [<generator object Tokenizer.cut at 0x7f90a84666d0>], [<generator object Tokenizer.cut at 0x7f90a8466750>], [<generator object Tokenizer.cut at 0x7f90a84667d0>], [<generator object Tokenizer.cut at 0x7f90a8466850>], [<generator object Tokenizer.cut at 0x7f90a84668d0>], [<generator object Tokenizer.cut at 0x7f90a8466a50>], [<generator object Tokenizer.cut at 0x7f90a84669d0>], [<generator object Tokenizer.cut at 0x7f90a8466dd0>], [<generator object Tokenizer.cut at 0x7f90a8466ad0>], [<generator object Tokenizer.cut at 0x7f90a8466b50>], [<generator object Tokenizer.cut at 0x7f90a8466bd0>], [<generator object Tokenizer.cut at 0x7f90a8466c50>], [<generator object Tokenizer.cut at 0x7f90a8466cd0>], [<generator object Tokenizer.cut at 0x7f90a8466d50>], [<generator object Tokenizer.cut at 0x7f90a8466950>], [<generator object Tokenize

word_to_idx：{'单词':序号,...}
idx_to_word：{序号:'单词',...}

In [ ]:

word_to_idx = {word: i for i, word in enumerate(vocb,1)}
idx_to_word = {word_to_idx[word]: word for word in word_to_idx}



In [ ]:
print(word_to_idx)
print(idx_to_word)

{'再慢': 1, '结合': 2, '不动': 3, '生活富裕': 4, '及': 5, '而言': 6, '黑死病': 7, '备战': 8, '相反': 9, '关键步骤': 10, '邱': 11, '虫子': 12, '其他同学': 13, '而是': 14, '毕博': 15, '权限': 16, '一人': 17, '不留': 18, '活水': 19, '宝贵时间': 20, '缺乏': 21, '多层次': 22, '能长点': 23, '区间': 24, '糊里糊涂': 25, '浅显易懂': 26, '白板': 27, '极少': 28, '平易近人': 29, '佛教': 30, '发声': 31, '显著': 32, '津津有味': 33, '真知': 34, '加倍努力': 35, '哪怕': 36, '巨头': 37, '安慰': 38, '课太水': 39, '入党': 40, '从事': 41, '面积': 42, 'der': 43, '雷同': 44, '全弄': 45, '吴恩达': 46, '简便': 47, '有愧': 48, '倩华': 49, '没写': 50, '相辅': 51, '导师': 52, '比较满意': 53, '初中': 54, '但是': 55, '鸡辣鸡': 56, '英语课': 57, '世界观': 58, '铜': 59, '途中': 60, '厌恶': 61, '加题': 62, '光电子': 63, '短期': 64, 'max': 65, '兄弟': 66, '出完': 67, '却说': 68, '混学': 69, '槽': 70, '上网': 71, '美国大学': 72, '地道': 73, '奋斗': 74, '正弦': 75, '蛮累': 76, '附有': 77, '归属感': 78, '杨晓临': 79, '星星': 80, '从我做起': 81, '哈哈哈哈': 82, '大开眼界': 83, '此外': 84, '选用': 85, '破网': 86, '职业技能': 87, '邓小平理论': 88, '°': 89, '百蔚': 90, '耳目一新': 91, '荣幸': 92, '延展': 93, '沒': 94, '第': 95, '课前': 96, 'f': 97

label标签

In [ ]:
labels = np.array(sentiment)
labels = labels.flatten()
print(labels)

[0 0 0 ... 1 1 1]


将评论分词后的词语一一转化为整数

In [ ]:

vocb_ints = []
for vocb in v:
    vocb_ints.append([word_to_idx[word] for word in vocb])

In [ ]:
print(vocb_ints[:1])

[[7303, 6262, 5533, 4626, 6869, 9149, 7147, 5304, 3920, 3920, 4501, 8573, 8072, 10176]]


In [ ]:
for i in vocb_ints[0]:
  print(idx_to_word[i],end='')


讲的能不能详细一点一个视频六分钟六分钟我就学会了

In [ ]:
length_v = []
for i in vocb_ints:
  length_v.append(len(i))
average_len = sum(length_v)/len(length_v)
print(average_len)
print(max(length_v))

12.59796730004419
262


## Padding sequences
将所有句子统一长度为50个单词：
1、评论长度小于50的，我们对其左边填充0
2、对于大于50的，我们只截取其前50个单词

In [ ]:
def pad_features(vocb_ints, seq_length):
    ''' Return features of review_ints, where each review is padded with 0's 
        or truncated to the input seq_length.
    '''
    
    # getting the correct rows x cols shape
    features = np.zeros((len(vocb_ints), seq_length), dtype=int)
    print(features.shape)
    # for each review, I grab that review and 
    for i, row in enumerate(vocb_ints):
        features[i, -len(row):] = np.array(row)[:seq_length]
    
    return features
 
 
 
# Test your implementation!
 
#选择每个句子长为50

seq_length = 50
 
features = pad_features(vocb_ints, seq_length=seq_length)
 
## test statements - do not change - ##
assert len(features)==len(vocb_ints), "Your features should have as many rows as reviews."
assert len(features[0])==seq_length, "Each feature row should contain seq_length values."
 
# print first 10 values of the first 30 batches 
print(features[:30,:10])

(11315, 50)
[[   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0   

### Training, Test划分

In [ ]:
split_frac = 0.8
 
## split data into training, validation, and test data (features and labels, x and y)
 
split_idx = int(len(features)*split_frac)
train_x, remaining_x = features[:split_idx], features[split_idx:]
train_y, remaining_y = labels[:split_idx], labels[split_idx:]
 
test_idx = int(len(remaining_x)*0.5)
val_x, test_x = remaining_x[:test_idx], remaining_x[test_idx:]
val_y, test_y = remaining_y[:test_idx], remaining_y[test_idx:]
 
## print out the shapes of your resultant feature data
print("\t\t\tFeature Shapes:")
print("Train set: \t\t{}".format(train_x.shape), 
      "\nValidation set: \t{}".format(val_x.shape),
      "\nTest set: \t\t{}".format(test_x.shape))

			Feature Shapes:
Train set: 		(9052, 50) 
Validation set: 	(1131, 50) 
Test set: 		(1132, 50)


或者

In [ ]:
# # 无运行，但他可以随机化
# from sklearn.model_selection import ShuffleSplit
# ss = ShuffleSplit(n_splits=1,test_size=0.2,random_state=1)
# for train_index,test_index in ss.split(np.array(vocb_ints)):
#     train_x = features[train_index]
#     train_y = labels[train_index]
#     test_x = features[test_index]
#     test_y = labels[test_index]
 
# print("\t\t\tFeature Shapes:")
# print("Train set: \t\t{}".format(train_x.shape), 
#       "\nTrain_Y set: \t{}".format(train_y.shape),
#       "\nTest set: \t\t{}".format(test_x.shape))

DataLoaders and Batching

In [ ]:
import torch
from torch.utils.data import TensorDataset, DataLoader
 
# create Tensor datasets
train_data = TensorDataset(torch.from_numpy(train_x), torch.from_numpy(train_y))
valid_data = TensorDataset(torch.from_numpy(val_x), torch.from_numpy(val_y))
test_data = TensorDataset(torch.from_numpy(test_x), torch.from_numpy(test_y))
 
# dataloaders
batch_size = 50

# make sure the SHUFFLE your training data
train_loader = DataLoader(train_data, shuffle=True, batch_size=batch_size,drop_last=True)
valid_loader = DataLoader(valid_data, shuffle=True, batch_size=batch_size,drop_last=True)
test_loader = DataLoader(test_data, shuffle=True, batch_size=batch_size,drop_last=True)

In [ ]:

# obtain one batch of training data
dataiter = iter(train_loader)
sample_x, sample_y = dataiter.next()
 
print('Sample input size: ', sample_x.size()) # batch_size, seq_length
print('Sample input: \n', sample_x)
print()
print('Sample label size: ', sample_y.size()) # batch_size
print('Sample label: \n', sample_y)


Sample input size:  torch.Size([50, 50])
Sample input: 
 tensor([[   0,    0,    0,  ..., 4590, 5854, 1851],
        [   0,    0,    0,  ..., 5037, 6255, 8207],
        [   0,    0,    0,  ..., 2992,  855,  160],
        ...,
        [   0,    0,    0,  ..., 6245, 3467,  969],
        [   0,    0,    0,  ..., 7202, 6111, 4423],
        [   0,    0,    0,  ..., 9320, 5292, 4232]])

Sample label size:  torch.Size([50])
Sample label: 
 tensor([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
        1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
        1, 1])


双向LSTM模型
1. 判断是否有GPU

In [ ]:
# First checking if GPU is available
train_on_gpu=torch.cuda.is_available()
 
if(train_on_gpu):
    print('Training on GPU.')
else:
    print('No GPU available, training on CPU.')

Training on GPU.


In [ ]:
import torch.nn as nn
 
class SentimentRNN(nn.Module):
    """
    The RNN model that will be used to perform Sentiment analysis.
    """
 
    def __init__(self, vocab_size, output_size, embedding_dim, hidden_dim, n_layers, bidirectional=True, drop_prob=0.5):
        """
        Initialize the model by setting up the layers.
        """
        super(SentimentRNN, self).__init__()
 
        self.output_size = output_size
        self.n_layers = n_layers
        self.hidden_dim = hidden_dim
        self.bidirectional = bidirectional
        
        # embedding and LSTM layers
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, n_layers, 
                            dropout=drop_prob, batch_first=True,
                            bidirectional=bidirectional)
        
        # dropout layer
        self.dropout = nn.Dropout(0.3)
        
        # linear and sigmoid layers
        if bidirectional:
          self.fc = nn.Linear(hidden_dim*2, output_size)
        else:
          self.fc = nn.Linear(hidden_dim, output_size)
          
        self.sig = nn.Sigmoid()
        
 
    def forward(self, x, hidden):
        """
        Perform a forward pass of our model on some input and hidden state.
        """
        batch_size = x.size(0)
 
        # embeddings and lstm_out
        x = x.long()
        embeds = self.embedding(x)
        lstm_out, hidden = self.lstm(embeds, hidden)
        
#         if bidirectional:
#           lstm_out = lstm_out.contiguous().view(-1, self.hidden_dim*2)
#         else:
#           lstm_out = lstm_out.contiguous().view(-1, self.hidden_dim)
       
        # dropout and fully-connected layer
        out = self.dropout(lstm_out)
        out = self.fc(out)
        # sigmoid function
        sig_out = self.sig(out)
        
        # reshape to be batch_size first
        sig_out = sig_out.view(batch_size, -1)
        sig_out = sig_out[:, -1] # get last batch of labels
        
        # return last sigmoid output and hidden state
        return sig_out, hidden
    
    
    def init_hidden(self, batch_size):
        ''' Initializes hidden state '''
        # Create two new tensors with sizes n_layers x batch_size x hidden_dim,
        # initialized to zero, for hidden state and cell state of LSTM
        weight = next(self.parameters()).data
        
        number = 1
        if self.bidirectional:
           number = 2
        
        if (train_on_gpu):
            hidden = (weight.new(self.n_layers*number, batch_size, self.hidden_dim).zero_().cuda(),
                      weight.new(self.n_layers*number, batch_size, self.hidden_dim).zero_().cuda()
                     )
        else:
            hidden = (weight.new(self.n_layers*number, batch_size, self.hidden_dim).zero_(),
                      weight.new(self.n_layers*number, batch_size, self.hidden_dim).zero_()
                     )
        
        return hidden

是否使用双向LSTM（在测试集上效果更好一些）





In [ ]:
# Instantiate the model w/ hyperparams
vocab_size = len(word_to_idx)+1  # +1 for the 0 padding + our word tokens
output_size = 1
embedding_dim = 400
hidden_dim = 256
n_layers = 2
bidirectional = True  #这里为True，为双向LSTM
 
net = SentimentRNN(vocab_size, output_size, embedding_dim, hidden_dim, n_layers, bidirectional)
 
print(net)

SentimentRNN(
  (embedding): Embedding(11064, 400)
  (lstm): LSTM(400, 256, num_layers=2, batch_first=True, dropout=0.5, bidirectional=True)
  (dropout): Dropout(p=0.3, inplace=False)
  (fc): Linear(in_features=512, out_features=1, bias=True)
  (sig): Sigmoid()
)


### train



In [ ]:
# loss and optimization functions
lr=0.001
 
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(net.parameters(), lr=lr)
 
 
# training params
 
epochs = 4 # 3-4 is approx where I noticed the validation loss stop decreasing
 
print_every = 100
clip=5 # gradient clipping
 
# move model to GPU, if available
if(train_on_gpu):
    net.cuda()
 
net.train()
# train for some number of epochs
for e in range(epochs):
    # initialize hidden state
    h = net.init_hidden(batch_size)
    counter = 0
 
    # batch loop
    for inputs, labels in train_loader:
        counter += 1
 
        if(train_on_gpu):
            inputs, labels = inputs.cuda(), labels.cuda()
 
        # Creating new variables for the hidden state, otherwise
        # we'd backprop through the entire training history
        h = tuple([each.data for each in h])
        # zero accumulated gradients
        net.zero_grad()
 
        # get the output from the model
        output, h = net(inputs, h)
 
        # calculate the loss and perform backprop
        loss = criterion(output.squeeze(), labels.float())
        loss.backward()
        # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
        nn.utils.clip_grad_norm_(net.parameters(), clip)
        optimizer.step()
 
        # loss stats
        if counter % print_every == 0:
            # Get validation loss
            val_h = net.init_hidden(batch_size)
            val_losses = []
            net.eval()
            for inputs, labels in valid_loader:
 
                # Creating new variables for the hidden state, otherwise
                # we'd backprop through the entire training history
                val_h = tuple([each.data for each in val_h])
 
                if(train_on_gpu):
                    inputs, labels = inputs.cuda(), labels.cuda()
 
                output, val_h = net(inputs, val_h)
                val_loss = criterion(output.squeeze(), labels.float())
 
                val_losses.append(val_loss.item())
 
            net.train()
            print("Epoch: {}/{}...".format(e+1, epochs),
                  "Step: {}...".format(counter),
                  "Loss: {:.6f}...".format(loss.item()),
                  "Val Loss: {:.6f}".format(np.mean(val_losses)))

Epoch: 1/4... Step: 100... Loss: 0.201941... Val Loss: 0.403813
Epoch: 2/4... Step: 100... Loss: 0.255696... Val Loss: 0.233555
Epoch: 3/4... Step: 100... Loss: 0.167464... Val Loss: 0.226663
Epoch: 4/4... Step: 100... Loss: 0.027723... Val Loss: 0.370728


### Test

In [ ]:
# Get test data loss and accuracy
 
test_losses = [] # track loss
num_correct = 0
 
# init hidden state
h = net.init_hidden(batch_size)
 
net.eval()
# iterate over test data
for inputs, labels in test_loader:
 
    # Creating new variables for the hidden state, otherwise
    # we'd backprop through the entire training history
    h = tuple([each.data for each in h])
 
    if(train_on_gpu):
        inputs, labels = inputs.cuda(), labels.cuda()
    
    # get predicted outputs
    output, h = net(inputs, h)
    
    # calculate loss
    test_loss = criterion(output.squeeze(), labels.float())
    test_losses.append(test_loss.item())
    
    # convert output probabilities to predicted class (0 or 1)
    pred = torch.round(output.squeeze())  # rounds to the nearest integer
    
    # compare predictions to true label
    correct_tensor = pred.eq(labels.float().view_as(pred))
    correct = np.squeeze(correct_tensor.numpy()) if not train_on_gpu else np.squeeze(correct_tensor.cpu().numpy())
    num_correct += np.sum(correct)
 
 
# -- stats! -- ##
# avg test loss
print("Test loss: {:.3f}".format(np.mean(test_losses)))
 
# accuracy over all test data
test_acc = num_correct/len(test_loader.dataset)
print("Test accuracy: {:.3f}".format(test_acc))

Test loss: 0.283
Test accuracy: 0.903


### 模型Inference

In [ ]:
# negative test review
test_review_neg = '这老师也太敷衍了吧'


In [ ]:

 
def tokenize_review(test_review):
    test_cut = jieba.cut(test_review) #分词
    test_words = [word for word in test_cut]  #输出jieba迭代器
    # get rid of punctuation

    # tokens
    test_ints = []
    test_ints.append([word_to_idx[word] for word in test_words])
 
    return test_ints
 
# test code and generate tokenized review
test_ints = tokenize_review(test_review_neg)
print(test_ints)
 
 
# test sequence padding
seq_length=200
features = pad_features(test_ints, seq_length)
print(features)
 
# test conversion to tensor and pass into your model
feature_tensor = torch.from_numpy(features)
print(feature_tensor.size())

[[9395, 160, 7202, 4384, 3098, 10176, 9875]]
(1, 200)
[[    0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0   

In [ ]:
def predict(net, test_review, sequence_length=50):
    
    net.eval()
    
    # tokenize review
    test_ints = tokenize_review(test_review)
    
    # pad tokenized sequence
    seq_length=sequence_length
    features = pad_features(test_ints, seq_length)
    
    # convert to tensor to pass into your model
    feature_tensor = torch.from_numpy(features)
    
    batch_size = feature_tensor.size(0)
    
    # initialize hidden state
    h = net.init_hidden(batch_size)
    
    if(train_on_gpu):
        feature_tensor = feature_tensor.cuda()
    
    # get the output from the model
    output, h = net(feature_tensor, h)
    
    # convert output probabilities to predicted class (0 or 1)
    pred = torch.round(output.squeeze()) 
    # printing output value, before rounding
    print('Prediction value, pre-rounding: {:.6f}'.format(output.item()))
    
    # print custom response
    if(pred.item()==1):
        print("Positive review detected!")
    else:
        print("Negative review detected.")

In [ ]:

 
# call function
seq_length=50 # good to use the length that was trained on
 
predict(net, test_review_neg, seq_length)

(1, 50)
Prediction value, pre-rounding: 0.005426
Negative review detected.


In [ ]:
# positive test review
test_review_pos = '这个课的老师讲的真不错'
predict(net, test_review_pos, seq_length)

(1, 50)
Prediction value, pre-rounding: 0.987223
Positive review detected!
